### ISSUE TITLE
Unable to generate medium dataset

### ISSUE THREAD

**Issue by svepe** [omron-sinicx/srsd-benchmark#1]
When following the instructions to generate the medium complexity dataset I get the following error:
```
Generating dataset `FeynmanIIICh14Eq14` ...
{'output_dir': './resource/datasets/srsd/medium_set/', 'output_ext': '.txt', 'sample_size': 10000, 'kwargs': None}
Traceback (most recent call last):
  File "/home/svet/.local/lib/python3.10/site-packages/ipdb/__main__.py", line 305, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.10/pdb.py", line 1586, in _runscript
    self.run(statement)
  File "/usr/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/svet/Projects/srsd-benchmark/dataset_generator.py", line 101, in <module>
    main(argparser.parse_args())
  File "/home/svet/Projects/srsd-benchmark/dataset_generator.py", line 96, in main
    generate_dataset(dataset_key, dataset_config, default_train_ratio, default_val_ratio, default_test_ratio)
  File "/home/svet/Projects/srsd-benchmark/dataset_generator.py", line 49, in generate_dataset
    dataset = eq_instance.create_dataset(dataset_config['sample_size'])
  File "/home/svet/Projects/srsd-benchmark/datasets/base.py", line 77, in create_dataset
    y = self.eq_func(xs)
  File "/home/svet/Projects/srsd-benchmark/datasets/feynman.py", line 2778, in eq_func
    return x[0] * (np.exp(x[1] * x[2] / (BOLTZMANN_CONSTANT * x[3])) - 1)
RuntimeWarning: overflow encountered in exp
```

Given the magnitude of the Boltzmann constant I am not too surprised the overflow is actually happening. How did you manage to generate the public versions of the dataset?

**Comment by yoshitomo-matsubara** [comment]
Hi @svepe 

Thank you for reporting the issue.
At first I confirmed that the published dataset works without the error.

```python
import os
import numpy as np

BOLTZMANN_CONSTANT = 1.380649e-23
x_train = np.loadtxt(os.path.expanduser('~/hf/srsd-feynman_medium/train/feynman-iii.14.14.txt'))
y_train = x_train[:, 0] * (np.exp(x_train[:, 1] * x_train[:, 2] / (BOLTZMANN_CONSTANT * x_train[:, 3])) - 1)

x_val = np.loadtxt(os.path.expanduser('~/hf/srsd-feynman_medium/val/feynman-iii.14.14.txt'))
y_val = x_val[:, 0] * (np.exp(x_val[:, 1] * x_val[:, 2] / (BOLTZMANN_CONSTANT * x_val[:, 3])) - 1)

x_test = np.loadtxt(os.path.expanduser('~/hf/srsd-feynman_medium/test/feynman-iii.14.14.txt'))
y_test = x_test[:, 0] * (np.exp(x_test[:, 1] * x_test[:, 2] / (BOLTZMANN_CONSTANT * x_test[:, 3])) - 1)

```

Note that `y_*` in the example above uses `x` in a different way as the input x_* is a raw matrix.

I also confirmed the same error with Python 3.8 and found that `warnings.filterwarnings('ignore')` in [datasets/base.py](https://github.com/omron-sinicx/srsd-benchmark/pull/2/files) we used was not reflected to the repository.
It excludes samples that cause [overflow/underflow/invalid input errors that result in nan](https://github.com/omron-sinicx/srsd-benchmark/blob/main/datasets/base.py#L90) from the set of generated samples and regenerate different samples to take the place of such problematic samples as implemented [here](https://github.com/omron-sinicx/srsd-benchmark/blob/main/datasets/base.py#L87-L97).

Now `datasets/base.py` is updated and has the approach we used.
Thank you for the help!

**Comment by svepe** [comment]
Thanks for the quick fix! I can confirm the dataset generation works fine now.
